---
apiVersion: v1
kind: Namespace
metadata:
  name: kwir

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigning-issuer
  namespace: kwir
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kube-webhook-image-rewriter-certs
  namespace: kwir
spec:
  secretName: kube-webhook-image-rewriter-certs
  dnsNames:
  - kube-webhook-image-rewriter.kwir.svc.cluster.local
  - kube-webhook-image-rewriter.kwir.svc
  issuerRef:
    name: selfsigning-issuer

---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: kube-webhook-image-rewriter
  annotations:
    cert-manager.io/inject-ca-from: kwir/kube-webhook-image-rewriter-certs
webhooks:
- name: kube-webhook-image-rewriter.kwir.svc
  admissionReviewVersions: ["v1"]
  failurePolicy: Fail
  sideEffects: None
  namespaceSelector:
    matchLabels:
      kwir-podrewriter-enabled: "true"
  clientConfig:
    caBundle: Cg==
    service:
      name: kube-webhook-image-rewriter
      namespace: kwir
      path: /kwir-mutate-v1-pod
  rules:
  - apiGroups: [""]
    apiVersions: ["v1"]
    operations: ["CREATE", "UPDATE"]
    resources: ["pods"]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kwir
  namespace: kwir
  labels:
    app: kwir
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kwir
  template:
    metadata:
      labels:
        app: kwir
    spec:
      containers:
      - name: kwir
        image: barthv/kwir
        imagePullPolicy: Always
        ports:
        - name: https
          containerPort: 9443
          protocol: TCP
        volumeMounts:
        - mountPath: /certs
          name: certs
        resources:
          limits:
            cpu: 20m
            memory: 64Mi
      volumes:
      - name: certs
        secret:
          secretName: kube-webhook-image-rewriter-certs

---
apiVersion: v1
kind: Service
metadata:
  name: kube-webhook-image-rewriter
  namespace: kwir
  labels:
    app: kube-webhook-image-rewriter
spec:
  ports:
  - port: 443
    targetPort: https
    protocol: TCP
  selector:
    app: kwir
