---
apiVersion: v1
kind: Namespace
metadata:
  name: test1
  labels:
    kwir-podrewriter-enabled: "true"

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: busybox
  namespace: test1
spec:
  serviceName: busybox
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: busybox:latest
        command:
        - sleep
        - "3600"

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: alpine
  namespace: test1
spec:
  serviceName: alpine
  replicas: 1
  selector:
    matchLabels:
      app: alpine
  template:
    metadata:
      labels:
        app: alpine
      annotations:
        "kwir/podrewriter-skip": "true"
    spec:
      containers:
      - name: alpine
        image: alpine:latest
        command:
        - sleep
        - "3600"
