name: test-build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x

      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.36
          args: --timeout=2m
          skip-go-installation: true

      - name: Build
        run: go build ./...

      - name: Test
        run: go test ./...
